export default class Const {
  static STUDENT_LIST_PENDING = 'STUDENT_LIST_PENDING';
  static STUDENT_LIST_FULFILLED = 'STUDENT_LIST_FULFILLED';
  static STUDENT_LIST_REJECTED = 'STUDENT_LIST_REJECTED';

  static DELETE_STUDENT_PENDING = 'DELETE_STUDENT_PENDING';
  static DELETE_STUDENT_FULFILLED = 'DELETE_STUDENT_FULFILLED';
  static DELETE_STUDENT_REJECTED = 'DELETE_STUDENT_REJECTED';
}
