export default class Const {
  static STUDENT_LIST_PENDING = 'STUDENT_LIST_PENDING';
  static STUDENT_LIST_FULFILLED = 'STUDENT_LIST_FULFILLED';
  static STUDENT_LIST_REJECTED = 'STUDENT_LIST_REJECTED';

  static DELETE_STUDENT_PENDING = 'DELETE_STUDENT_PENDING';
  static DELETE_STUDENT_FULFILLED = 'DELETE_STUDENT_FULFILLED';
  static DELETE_STUDENT_REJECTED = 'DELETE_STUDENT_REJECTED';

  static ADD_STUDENT_PENDING = 'ADD_STUDENT_PENDING';
  static ADD_STUDENT_FULFILLED = 'ADD_STUDENT_FULFILLED';
  static ADD_STUDENT_REJECTED = 'ADD_STUDENT_REJECTED';

  static UPDATE_STUDENT_PENDING = 'UPDATE_STUDENT_PENDING';
  static UPDATE_STUDENT_FULFILLED = 'UPDATE_STUDENT_FULFILLED';
  static UPDATE_STUDENT_REJECTED = 'UPDATE_STUDENT_REJECTED';

  static UPLOAD_STUDENT_EXCEL_PENDING = 'UPLOAD_STUDENT_EXCEL_PENDING';
  static UPLOAD_STUDENT_EXCEL_FULFILLED = 'UPLOAD_STUDENT_EXCEL_FULFILLED';
  static UPLOAD_STUDENT_EXCEL_REJECTED = 'UPLOAD_STUDENT_EXCEL_REJECTED';

  static DOWNLOAD_STUDENT_EXCEL_PENDING = 'DOWNLOAD_STUDENT_EXCEL_PENDING';
  static DOWNLOAD_STUDENT_EXCEL_FULFILLED = 'DOWNLOAD_STUDENT_EXCEL_FULFILLED';
  static DOWNLOAD_STUDENT_EXCEL_REJECTED = 'DOWNLOAD_STUDENT_EXCEL_REJECTED';
}
