export default class Const {
  static TEACHER_LIST_PENDING = 'TEACHER_LIST_PENDING';
  static TEACHER_LIST_FULFILLED = 'TEACHER_LIST_FULFILLED';
  static TEACHER_LIST_REJECTED = 'TEACHER_LIST_REJECTED';

  static DELETE_TEACHER_PENDING = 'DELETE_TEACHER_PENDING';
  static DELETE_TEACHER_FULFILLED = 'DELETE_TEACHER_FULFILLED';
  static DELETE_TEACHER_REJECTED = 'DELETE_TEACHER_REJECTED';

  static ADD_TEACHER_PENDING = 'ADD_TEACHER_PENDING';
  static ADD_TEACHER_FULFILLED = 'ADD_TEACHER_FULFILLED';
  static ADD_TEACHER_REJECTED = 'ADD_TEACHER_REJECTED';

  static UPDATE_TEACHER_PENDING = 'UPDATE_TEACHER_PENDING';
  static UPDATE_TEACHER_FULFILLED = 'UPDATE_TEACHER_FULFILLED';
  static UPDATE_TEACHER_REJECTED = 'UPDATE_TEACHER_REJECTED';

  static UPLOAD_TEACHER_EXCEL_PENDING = 'UPLOAD_TEACHER_EXCEL_PENDING';
  static UPLOAD_TEACHER_EXCEL_FULFILLED = 'UPLOAD_TEACHER_EXCEL_FULFILLED';
  static UPLOAD_TEACHER_EXCEL_REJECTED = 'UPLOAD_TEACHER_EXCEL_REJECTED';

  static DOWNLOAD_TEACHER_EXCEL_PENDING = 'DOWNLOAD_TEACHER_EXCEL_PENDING';
  static DOWNLOAD_TEACHER_EXCEL_FULFILLED = 'DOWNLOAD_TEACHER_EXCEL_FULFILLED';
  static DOWNLOAD_TEACHER_EXCEL_REJECTED = 'DOWNLOAD_TEACHER_EXCEL_REJECTED';
}
